WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/ProcessedBlock.cs
namespace WebApp.Models
{
    public class ProcessedBlock
    {
        public int Number { get; set; }
        public int TransactionsFound { get; set; }
        public List<string> RelatedAddresses { get; set; } = new List<string>();
    }
}

WebApp/Models/SnapshotRequestViewModel.cs
namespace WebApp.Models
{
    public class SnapshotRequestViewModel
    {
        public string Address { get; set; }
        public int StartBlock { get; set; }
        public int EndBlock { get; set; }  

    }
}

WebApp/Models/SnapshotResultViewModel.cs
namespace WebApp.Models
{
    public class SnapshotResultViewModel
    {
        public string Id { get; set; }
        public List<ProcessedBlock> Blocks { get; set; } = new();
    }
}

WebApp/Models/TokenHolderViewModel.cs
namespace WebApp.Models
{
    public class TokenHolderViewModel
    {
        public string Address { get; set; }
        public long Amount { get; set; }
    }
}

WebApp/Models/TokenTradesViewModel.cs
namespace WebApp.Models
{
    public class Transfer
    {
        public int Source { get; set; }
        public int Target { get; set; }
        public long Amount { get; set; }
    }

    public class TransferNode
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class TokenTradesViewModel
    {
        public List<TransferNode> TransferNodes { get; set; }
        public List<Transfer> Transfers { get; set; }
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/SnapshotController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SnapshotController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult TakeSnapshot([FromForm] SnapshotRequestViewModel request)
        {
            StartSnapshot(request);
            return View(request);
        }

        private void StartSnapshot(SnapshotRequestViewModel request)
        {

        }

        public SnapshotResultViewModel GetResult()
        {
            return new SnapshotResultViewModel
            {
                Id = "snapshot1",
                Blocks = {
                    new ProcessedBlock(){Number =1, TransactionsFound = 0, RelatedAddresses = new()},
                    new ProcessedBlock(){Number =2, TransactionsFound = 4, RelatedAddresses = new(){"a", "b", "c"}},
                    new ProcessedBlock(){Number =3, TransactionsFound = 2, RelatedAddresses = new(){"a", "b" }}
                }
            };
        }

        public List<TokenHolderViewModel> GetTokenHolders()
        {
            return new List<TokenHolderViewModel>()
            {
                new TokenHolderViewModel(){Address ="A", Amount=500},
                new TokenHolderViewModel(){Address ="B", Amount=100},
                new TokenHolderViewModel(){Address ="C", Amount=2500},
                new TokenHolderViewModel(){Address ="D", Amount=1500},
            };
        }

        public TokenTradesViewModel GetTokenTransfers()
        {
            return new TokenTradesViewModel()
            {
                TransferNodes = new() { 
                    new() { Id = 1, Name = "A" },
                    new() { Id = 2, Name = "B" },
                    new() { Id = 3, Name = "C" }, 
                    new() { Id = 4, Name = "D" },
                    new() { Id = 5, Name = "E" }
                },
                Transfers = new()
                {
                    new Transfer() { Source = 1, Target = 4, Amount = 500 },
                    new Transfer() { Source = 2, Target = 4, Amount = 100 },
                    new Transfer() { Source = 3, Target = 1, Amount = 2500 },
                    new Transfer() { Source = 4, Target = 3, Amount = 1500 },
                    new Transfer() { Source = 4, Target = 5, Amount = 5500 }
                }
            };
        }

        public bool IsSnapshotRunning()
        {
            return true;
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/d3-color.v1.min.js"></script>
    <script src="https://d3js.org/d3-dispatch.v1.min.js"></script>
    <script src="https://d3js.org/d3-ease.v1.min.js"></script>
    <script src="https://d3js.org/d3-interpolate.v1.min.js"></script>
    <script src="https://d3js.org/d3-selection.v1.min.js"></script>
    <script src="https://d3js.org/d3-timer.v1.min.js"></script>
    <script src="https://d3js.org/d3-transition.v1.min.js"></script>
    <script src="https://d3js.org/d3-selection-multi.v1.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Snapshot" asp-action="Index">Snapshot</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Snapshot/Index.cshtml
@model SnapshotRequestViewModel

<div class="row mx-5">
        <div class="w-100 py-2 px-4 rounded-borders-top bg-lightgrey">
            <h4 >Start a new snapshot</h4>
        </div>
        <div class="py-3 px-3 rounded-borders-bottom border-color-lightgrey">
            <form asp-action="TakeSnapshot" >
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-6 col-xl-6 mb-4">
                        <p class="fw-bold">Contract</p>
                        <label for="address" class="form-label fw-lighter">Address</label>
                        <input asp-for="Address" name="address" class="form-control" type="text"/>
                    </div>
                    <div class="col-12 col-md-12 col-xl-6">
                        <p class="fw-bold">Blocks</p>
                        <div class="row">
                            <div class="col-6 col-xl-5 mb-2">
                                <label for="startBlock" class="form-label fw-lighter">Start at</label>
                                <input asp-for="StartBlock" name="startBlock" class="form-control" type="number"/>
                            </div>
                            <div class="col-6 col-xl-5 mb-2">
                                <label for="endBlock" class="form-label fw-lighter">End at</label>
                                <input asp-for="EndBlock" name="endBlock" class="form-control" type="number"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <button class="btn-primary" type="submit">Scan</button>
                </div>
            </form>
        </div>
    </div>